package com.shalashgroup;
// Generated Jun 30, 2015 10:35:11 PM by Hibernate Tools 3.6.0



/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private Integer patientId;
     private String patientName;
     private String patientCase;

    public Patient() {
    }

    public Patient(String patientName, String patientCase) {
       this.patientName = patientName;
       this.patientCase = patientCase;
    }
   
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public String getPatientName() {
        return this.patientName;
    }
    
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }
    public String getPatientCase() {
        return this.patientCase;
    }
    
    public void setPatientCase(String patientCase) {
        this.patientCase = patientCase;
    }




}


